version: "3.8"

services:
  bot-kairos:
    build: .
    container_name: bot-kairos
    env_file:
      - .env
    environment:
      - TZ=Europe/Paris
    depends_on:
      - bot-db-kairos
    restart: unless-stopped

  bot-db-kairos:
    image: mysql:latest
    container_name: bot-db-kairos
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      TZ: Europe/Paris
    volumes:
      - bot-db-kairos:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  bot-db-kairos:
