INSERT INTO Country VALUES
    ('#00', '"International Date Line West"', -12.0),
    ('#01', '"Midway Island, Samoa"', -11.0),
    ('#02', '"Hawaii"', -10.0),
    ('#03', '"Alaska"', -9.0),
    ('#04', '"Pacific Time (US & Canada)"', -8.0),
    ('#05', '"Mountain Time (US & Canada)"', -7.0),
    ('#06', '"Central Time (US & Canada), Mexico City"', -6.0),
    ('#07', '"Eastern Time (US & Canada), Bogota, Lima"', -5.0),
    ('#08', '"Atlantic Time (Canada), Caracas, La Paz"', -4.0),
    ('#09', '"Newfoundland"', -3.5),
    ('#10', '"Brazil, Buenos Aires, Georgetown"', -3.0),
    ('#11', '"Mid-Atlantic"', -2.0),
    ('#12', '"Azores, Cape Verde Islands"', -1.0),
    ('#13', '"Western Europe Time, London, Lisbon, Casablanca"', 0.0),
    ('#14', '"Brussels, Copenhagen, Madrid, Paris"', 1.0),
    ('#15', '"Kaliningrad, South Africa"', 2.0),
    ('#16', '"Baghdad, Riyadh, Moscow, St. Petersburg"', 3.0),
    ('#17', '"Tehran"', 3.5),
    ('#18', '"Abu Dhabi, Muscat, Baku, Tbilisi"', 4.0),
    ('#19', '"Kabul"', 4.5),
    ('#20', '"Ekaterinburg, Islamabad, Karachi, Tashkent"', 5.0),
    ('#21', '"Bombay, Calcutta, Madras, New Delhi"', 5.5),
    ('#22', '"Kathmandu"', 5.75),
    ('#23', '"Almaty, Dhaka, Colombo"', 6.0),
    ('#24', '"Yangon, Bangkok, Hanoi, Jakarta"', 6.5),
    ('#25', '"Bangkok, Hanoi, Jakarta"', 7.0),
    ('#26', '"Beijing, Perth, Singapore, Hong Kong"', 8.0),
    ('#27', '"Tokyo, Seoul, Osaka, Sapporo, Yakutsk"', 9.0),
    ('#28', '"Darwin"', 9.5),
    ('#29', '"Eastern Australia, Guam, Vladivostok"', 10.0),
    ('#30', '"Magadan, Solomon Islands, New Caledonia"', 11.0),
    ('#31', '"Auckland, Wellington, Fiji, Kamchatka"', 12.0);
