name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."
          exit 1  # Simule une erreur pour tester le webhook

      - name: Send Discord notification on failure
        if: failure()
        run: |
          PAYLOAD=$(jq -n --arg content "1V1 Luca https://link.chess.com/play/RnGt9E)
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" ${{ secrets.DISCORD_WEBHOOK_URL }}
